---
GUP_ENVIRONMENT: production
GUP_OAUTH2_CLIENT_ID: 8a20983a-41e8-4f6c-b92d-99ba26307bf0
GUP_REPOSITORY_NAME: Gothenburg University Publications (GUP)
GUP_OAI_REPOSITORY_NAME: GUP
GUP_OAI_RECORD_PREFIX: oai:gup.ub.gu.se
GUP_SMTP_SERVER: dockerhem.ub.gu.se
GUP_SMTP_PORT: 9025
GUP_MAIL_FROM: noreply@ub.gu.se
GUP_MAIL_TO: gup@ub.gu.se
