$ANSIBLE_VAULT;1.1;AES256
66656264663337633761646638366364356262306664636361623661373735303366353837343839
3863313438306165643931616434633434306365363838340a343161643861633135306435393435
32333739323361646238346565616130323234613164386666626533386531343663653636303630
6638613534653630660a323032666533653462613931653661633132303761386561393766376565
66356362616630323861313032343166336261333139383536353131333364613463313138653733
33393638323637663362626239336634373964623339396337353432616361303362646136663337
38663430313931356163663864336438366233313038643036313233366639663631303035653439
65306461666532666166663537303233666664666234323039623464663633363637663766636432
31376466356539666535613136326432343633376138313733653434363561356533663138346566
33343731616564636561633534376332626434373464613362643731623533303562613163623036
66373338616332346436633238633666393232346537656664653235373661353266626664623761
62646561613761383630303231653262666333376434313564303138623261383934623539353963
65306661663439666632356463376261336434346533373434383865373361623564376562303366
66353836353564393035643065616639623861633331643530396536333862313532393761313531
61313064393366646565353763653635373635636665636166363862393438346666383261393033
34343635623965656166363665376330333539306632343234346638376631376664393335666237
65666566626530323866663861363062313433313730303062373266653239633931336138356566
32623135356530393234306130616130313962383534373839643738663363383464383530333734
30663566383632636565353834636665323862303563353265313464306532373038376238326363
64353633383539613962616130316236633264396232323863386434383235303662643534396538
37336165393033336137336235633832393261386563323831623633316239366234646166303234
37396630643230623032333662303636663565386634386333356162643166386635343831383539
393565666266656236363137333037313133
