---
GIT_REVISION: '{{ git_revision }}'
GUP_FRONTEND_PORT: '127.0.0.1:{{ frontend_host_port }}'
GUP_BACKEND_PORT: '127.0.0.1:{{ backend_host_port }}'
GUP_BACKEND_FULL_PORT: '127.0.0.1:{{ backend_full_host_port }}'
GUP_SOLR_PORT: '127.0.0.1:{{ solr_host_port }}'
BACKEND_HOSTNAME: '{{ backend_hostname }}'
FRONTEND_HOSTNAME: '{{ frontend_hostname }}'
GUP_ENVIRONMENT: production

DEV_ALLOW_ALL_ACCOUNTS: "false"
DEV_OVERRIDE_ADMIN: ""

GUP_GUPEA_OAI_BASE_URL: https://gupea.ub.gu.se/dspace-oai/request
GUP_GUPEA_OAI_METADATA_PREFIX: scigloo
GUP_GUPEA_OAI_IDENTIFIER_PREFIX: oai:gupea.ub.gu.se

GUP_ADMIN_PERSON_ENABLE: "true"
GUP_ADMIN_PUBLICATION_ENABLE: "true"

GUP_DB_HOST: gup-db
GUP_DB_PORT: 5432
GUP_DB: gup_db
GUP_DB_USER: gup_user
GUP_DB_PASSWORD: gup_pass
GUP_MAX_NUMBER_OF_POSTS_RIS: 10000
GUP_PUBLIC_BASE_URL: "https://{{ frontend_hostname }}"

BACKEND_OAI_HOSTNAME: "{{ frontend_hostname }}"
BACKEND_OAI_FULL_HOSTNAME: "{{ frontend_hostname }}"

GUP_BACKEND_UPLOADS_VOLUME_SOURCE: "{{ data_dirs.backend_uploads.path }}"
GUP_BACKEND_SITEMAPS_DIR: "{{ data_dirs.backend_sitemaps.path }}"
GUP_DB_VOLUME_SOURCE: "{{ data_dirs.backend_db.path }}"
GUP_SOLR_JOURNALS_VOLUME_SOURCE: "{{ data_dirs.solr_journals.path }}"
GUP_SOLR_PEOPLE_VOLUME_SOURCE: "{{ data_dirs.solr_people.path }}"
GUP_SOLR_PUBLICATIONS_VOLUME_SOURCE: "{{ data_dirs.solr_publications.path }}"

GUP_STATIC_RUNNING_IMAGE: "{{ apache_static_image }}"
GUP_STATIC_ACCESS_PORT: "127.0.0.1:{{ apache_static_host_port }}"
GUP_STATIC_APACHE_SITE: "{{ data_dirs.apache_static_sites.path }}"

GUP_OAUTH2_PROVIDER: gu
GUP_OAUTH2_AUTHORIZE_ENDPOINT: https://idp.auth.gu.se/adfs/oauth2/authorize/
GUP_OAUTH2_TOKEN_ENDPOINT: https://idp.auth.gu.se/adfs/oauth2/token/
GUP_OAUTH2_USER_ENDPOINT: https://idp.auth.gu.se/adfs/userinfo

GUP_MQ_BASE_URL: http://130.241.35.194:12345/gup
GUP_ADMIN_BASE_URL: http://index-manager-backend:4000

GUP_SMTP_SERVER: smtpgw.gu.se
GUP_SMTP_PORT: 587
GUP_MAIL_FROM: noreply@ub.gu.se
GUP_MAIL_TO: johan.larsson@ub.gu.se
