---
GUP_ENVIRONMENT: lab
GUP_ADMIN_BASE_URL: http://index-manager-backend:4000
GUP_OAUTH2_CLIENT_ID: Ov23lifuepovjGdq5oWc
GUP_OAUTH2_PROVIDER: github
GUP_OAUTH2_AUTHORIZE_ENDPOINT: https://github.com/login/oauth/authorize
GUP_OAUTH2_TOKEN_ENDPOINT: https://github.com/login/oauth/access_token
GUP_OAUTH2_USER_ENDPOINT: https://api.github.com/user
GUP_REPOSITORY_NAME: Gothenburg University Publications (GUP) - dev
GUP_OAI_REPOSITORY_NAME: GUP - dev
GUP_OAI_RECORD_PREFIX: oai:gup-dev.ub.gu.se
GUP_MQ_BASE_URL: http://130.241.35.194:12345/gup
GUP_SMTP_SERVER: smtpgw.gu.se
GUP_SMTP_PORT: 587
GUP_MAIL_FROM: noreply@ub.gu.se
GUP_MAIL_TO: johan.larsson@ub.gu.se
DEV_ALLOW_ALL_ACCOUNTS: true
DEV_OVERRIDE_ADMIN: ub-digit
