---
GUP_ENVIRONMENT: lab
GUP_OAUTH2_CLIENT_ID: Ov23lifuepovjGdq5oWc
GUP_REPOSITORY_NAME: Gothenburg University Publications (GUP) - dev
GUP_OAI_REPOSITORY_NAME: GUP - dev
GUP_OAI_RECORD_PREFIX: oai:gup-dev.ub.gu.se
DEV_ALLOW_ALL_ACCOUNTS: "true"
DEV_OVERRIDE_ADMIN: ub-digit
