---
GUP_ENVIRONMENT: lab
GUP_OAUTH2_CLIENT_ID: 6545cfd6-eea3-4f7d-bc79-d7b9816dc10c
GUP_REPOSITORY_NAME: Gothenburg University Publications (GUP) - lab
GUP_OAI_REPOSITORY_NAME: GUP - lab
GUP_OAI_RECORD_PREFIX: oai:gup-lab.ub.gu.se
DEV_ALLOW_ALL_ACCOUNTS: "true"
DEV_OVERRIDE_ADMIN: ub-digit
